#数字化工艺系统IB1数据库

# set table IB1
DROP TABLE IF EXISTS `IB1_Basic`;
CREATE TABLE `IB1_Basic`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如1.7',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',

`IB1_RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如11.07.2019',
`IB1_IBN-REQUIRED` VARCHAR(20) NOT NULL COMMENT '例如true',

`IB1_DOC-INFO_DOC-REVISIONS_DOC-REVISION` VARCHAR(50) COMMENT '例如VERSION',
`IB1_IB-DESCRIPTION` VARCHAR(50) COMMENT '例如IB-VARIANTS',
`IB1_ENVIRONMENT` VARCHAR(50) COMMENT '例如PRE-CONDITIONS',
`IB1_PROCEDURES_BLOCK` VARCHAR(50) COMMENT '例如KD-relevant',
`IB1_BZD_IDENTS_IDENT` VARCHAR(50) COMMENT '例如NAME',
`IB1_REFERENCES_RELATED-DOCUMENTS_RELATED-DOCUMENT` VARCHAR(50) COMMENT '例如NAME',


`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================

DROP TABLE IF EXISTS `IB1_DOC-INFO_DOC-REVISIONS_DOC-REVISION`;
CREATE TABLE `IB1_DOC-INFO_DOC-REVISIONS_DOC-REVISION`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如1.7',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',

`DOC-REVISION_VERSION` VARCHAR(50) NOT NULL COMMENT '例如1_2_DRAFT_1',
`DOC-REVISION_DATE` VARCHAR(20) NOT NULL COMMENT '例如07.08.2018',
`DOC-REVISION_CHANGE` VARCHAR(50) COMMENT '例如diverse Korrekturen',
`DOC-REVISION_TOOL` VARCHAR(50) COMMENT '例如IPPP_V4',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
DROP TABLE IF EXISTS `IB1_IB-DESCRIPTION`;
CREATE TABLE `IB1_IB-DESCRIPTION`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`VALIDITIES-REF` VARCHAR(100) NOT NULL COMMENT '例如IB1_0009_SAM_MEB_V1_7.tnr',
`OBJECTIVES_OBJECTIVE` VARCHAR(2000) COMMENT '例如Schutz der Fahrzeugdiagnose freischalten',
`IBNZ` VARCHAR(100) COMMENT '例如IBNZ-ESTIMATION',
`SLAVES` VARCHAR(100) COMMENT '例如NAME',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
-- DROP TABLE IF EXISTS `IB1_IB-DESCRIPTION_IBNZ`;
-- CREATE TABLE `IB1_IB-DESCRIPTION_IBNZ`(
-- `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
-- `IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
-- `IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',
-- 
-- `IBNZ_IBNZ-ESTIMATION` DOUBLE(12,6) COMMENT '例如157.0',
-- `IBNZ_IBNZ-COMMITMENT` DOUBLE(12,6) COMMENT '例如157.0',
-- 
-- `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
-- `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
-- PRIMARY KEY(`id`)
-- )ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
-- DROP TABLE IF EXISTS `IB1_IB-DESCRIPTION_SLAVES`;
-- CREATE TABLE `IB1_IB-DESCRIPTION_SLAVES`(
-- `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
-- `IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
-- `IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',
-- 
-- `SLAVE_NAME` VARCHAR(200) NOT NULL COMMENT '例如LIN-Dachkonsole LINDa',
-- `SLAVE_ECU-ID` VARCHAR(20) NOT NULL COMMENT '例如0626',
-- 
-- `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
-- `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
-- PRIMARY KEY(`id`)
-- )ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
DROP TABLE IF EXISTS `IB1_ENVIRONMENT`;
CREATE TABLE `IB1_ENVIRONMENT`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`PRE-CONDITIONS_PRE-CONDITION` VARCHAR(50) COMMENT 'IB1版本，例如3.24',
`DEPENDENCIES_DEPENDENCY` VARCHAR(50) COMMENT 'IB1版本，例如3.24',
`ACCESS-AUTHORISATIONS_ACCESS-AUTHORISATION` VARCHAR(50) COMMENT 'IB1版本，例如3.24',
`PRODUCTION-MODES_PRODUCTION-MODE` VARCHAR(50) COMMENT 'IB1版本，例如3.24',

`TRANSPORT-MODE` VARCHAR(1000) COMMENT '例如Die Funktionen Außenlicht Heck, In',


`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB1_ENVIRONMENT_PRE-CONDITIONS_PRE-CONDITION`;
CREATE TABLE `IB1_ENVIRONMENT_PRE-CONDITIONS_PRE-CONDITION`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

#`uuid` VARCHAR(50) NOT NULL COMMENT 'uuid_246bf6a9-c5b8-41da-9f43-193901667902_3',

`kdRelevant` VARCHAR(20) COMMENT '例如true',
`pRelevant` VARCHAR(20) COMMENT '例如true',
`text` VARCHAR(200) COMMENT '例如Fahrgeschwindigkeit:negative Testbedingung',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB1_ENVIRONMENT_DEPENDENCIES_DEPENDENCY`;
CREATE TABLE `IB1_ENVIRONMENT_DEPENDENCIES_DEPENDENCY`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`DEPENDENCY_id` INT(11) COMMENT '例如1',
`text` VARCHAR(200) COMMENT '例如Verbauänderung am Komfort CAN bzw. SubCAN',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB1_ENVIRONMENT_ACCESS-AUTHORISATIONS_ACCESS-AUTHORISATION`;
CREATE TABLE `IB1_ENVIRONMENT_ACCESS-AUTHORISATIONS_ACCESS-AUTHORISATION`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`NAME` VARCHAR(100) COMMENT '例如SFD',
`DESC` VARCHAR(1000) COMMENT '例如Diagnose wird über SFD geschützt',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_ENVIRONMENT_PRODUCTION-MODES_PRODUCTION-MODE`;
CREATE TABLE `IB1_ENVIRONMENT_PRODUCTION-MODES_PRODUCTION-MODE`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`NAME` VARCHAR(100) COMMENT '例如p_mode_parking_coordinator',
`DESC` VARCHAR(1000) COMMENT '例如PaCo: P-Mode ParkkoordinatorDeaktivierung',
`BYTES` VARCHAR(50) COMMENT '例如xxxxxxx1',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_ENVIRONMENT_PRODUCTION-MODES_PRODUCTION-MODE_BYTES`;
CREATE TABLE `IB1_ENVIRONMENT_PRODUCTION-MODES_PRODUCTION-MODE_BYTES`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`PRODUCTION-MODE_id` INT(11) NOT NULL COMMENT 'PRODUCTION-MODE_id',

`BYTE-0` VARCHAR(50) COMMENT '例如xxxxxxx1',
`BYTE-1` VARCHAR(50) COMMENT '例如xxxxxxxx',
`BYTE-2` VARCHAR(50) COMMENT '例如xxxxxxxx',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================


DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',
`NAME` VARCHAR(100) COMMENT 'IB1 name，例如 Inbetriebnahme-Ablauf Gateway',

`BLOCK_KD-relevant` VARCHAR(20) NOT NULL COMMENT '例如ture',
`BLOCK_P-relevant` VARCHAR(20) NOT NULL COMMENT '例如ture',
`BLOCK_optional` VARCHAR(20) NOT NULL COMMENT '例如ture',
`BLOCK_shortname` VARCHAR(50) COMMENT '例如UnlockSfd',
`BLOCK_standardIBNB` VARCHAR(20) COMMENT '例如ture',
`BLOCK_version` VARCHAR(20) COMMENT '例如1',
`BLOCK_NAME` VARCHAR(100) COMMENT '例如SFD freischalten',
`BLOCK_NAME_EN` VARCHAR(100) COMMENT '例如SFD unlock',
`BLOCK_DESC` VARCHAR(2000) COMMENT '例如Der Schutz der Fahrzeugdiagnose (SFD) wird ',
`BLOCK_TIS_TI_TI` VARCHAR(100) COMMENT '例如SER00098',
`BLOCK_CATEGORY` VARCHAR(100) COMMENT '例如Inbetriebnahme (konstruktiv bedingt)',
`BLOCK_TAGS_TAG` VARCHAR(100) COMMENT '例如IBNZ VSI-Wert aus Gateway MQB37W',
`BLOCK_AREA` VARCHAR(100) COMMENT '例如No Recommendation',
`BLOCK_LOGICAL-LINK` VARCHAR(50) COMMENT '例如GatewUDS',

`BLOCK_PARAMETERS_PARAMETER` VARCHAR(20) COMMENT '例如optional',


`BLOCK_CONDITIONS_MANUAL-OPERATIONS` VARCHAR(20) COMMENT '例如false',


`BLOCK_IBNZ_VSI` DOUBLE(12,6) COMMENT '例如0.312',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================


DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETER`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETER`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',


`BLOCK_PARAMETERS_PARAMETER_optional` VARCHAR(20) COMMENT '例如ture',
`BLOCK_PARAMETERS_PARAMETER_KEY` VARCHAR(100) COMMENT '例如Aufstartzeit',
`BLOCK_PARAMETERS_PARAMETER_DESC` VARCHAR(100) COMMENT '例如Aufstartzeit in Sekunden',
`BLOCK_PARAMETERS_PARAMETER_DATATYPE` VARCHAR(100) COMMENT '例如Integer',
`BLOCK_PARAMETERS_PARAMETER_VALUE` VARCHAR(100) COMMENT '例如&lt;1',
`BLOCK_PARAMETERS_PARAMETER_DEFAULT` VARCHAR(50) COMMENT '例如2',


`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`cyclic` VARCHAR(20) COMMENT '例如false',
`NAME` VARCHAR(100) COMMENT '例如VW/Audi-Teilenummer lesen',
`DESC` VARCHAR(1000) COMMENT '例如Fuer die Ermittlung des Herstellercodes (HSC)',
`DIAG-SERVICE` VARCHAR(100) COMMENT '例如SERVICE-IDENTIFIER',
`DIAG-PARAMETERS` VARCHAR(100) COMMENT '例如DATA-IDENTIFIER',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG-SERVICE`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG-SERVICE`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`IB1_STEP_id` INT(11) NOT NULL COMMENT 'IB1_step_id',
`SERVICE-IDENTIFIER` VARCHAR(20) COMMENT '例如22',
`SERVICE-LONG-NAME` VARCHAR(100) COMMENT '例如Read Data By Identifier / ECU Identification',
`SERVICE-SHORT-NAME` VARCHAR(100) COMMENT '例如DiagnServi_ReadDataByIdentECUIdent',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG-PARAMETERS`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG-PARAMETERS`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`IB1_STEP_id` INT(11) NOT NULL COMMENT 'IB1_step_id',

`DATA-IDENTIFIER_id` INT(11) COMMENT '例如1',
`DATA-IDENTIFIER` VARCHAR(20) COMMENT '例如F187',
`LONG-NAME` VARCHAR(100) COMMENT '例如Record Data Identifier',
`SHORT-NAME` VARCHAR(100) COMMENT '例如Param_RecorDataIdent',
`MESSAGE-TYPE` VARCHAR(100) COMMENT '例如REQUEST',
`RESPONSE-SHORT-NAME` VARCHAR(100) COMMENT '例如Resp_ReadDataByIdentECUIdent',
`PATH` VARCHAR(100) COMMENT '例如Param_RecorDataIdent',
`DATATYPE` VARCHAR(100) COMMENT '例如eTEXTTABLE',
`VALUE-PROXY_VALUE` VARCHAR(100) COMMENT '例如VW Spare Part Number',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_BZD`;
CREATE TABLE `IB1_BZD`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`S42-ATTRIBUTES-ADDED` VARCHAR(20) COMMENT '例如false',
`IDENTS_IDENT_NAME` VARCHAR(100) COMMENT '例如TBD',
`IDENTS_IDENT_S42-ATTRIBUTE` VARCHAR(100) COMMENT '例如TBD',
`IDENTS_IDENT_BGONLINE` VARCHAR(100) COMMENT '例如TBD',
`IDENTS_IDENT_DID` VARCHAR(100) COMMENT '例如TBD',
`TARGET-DATE` VARCHAR(20) COMMENT '例如31.08.2018',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_REFERENCES_RELATED-DOCUMENTS_RELATED-DOCUMENT`;
CREATE TABLE `IB1_REFERENCES_RELATED-DOCUMENTS_RELATED-DOCUMENT`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB1_NAME` VARCHAR(100) NOT NULL COMMENT 'IB1 name，例如 0009_SAM_MEB',
`IB1_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',

`NAME` VARCHAR(50) COMMENT '例如Zusatzschaltplan',
`VERSION` VARCHAR(50) COMMENT '例如TBD',
`FILE-SYSTEM` VARCHAR(50) COMMENT 'System42',
`SPARE-PART-NUMBER` VARCHAR(200) COMMENT 'TLD.011.179.B0',
`URL` VARCHAR(500) COMMENT 'https://iproject3.wob.vw.vwg/vw',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
DROP TABLE IF EXISTS `test666`;
CREATE TABLE `test666`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`VERSION` VARCHAR(50) NOT NULL COMMENT 'IB1版本，例如3.24',
`test` DOUBLE(12,6) COMMENT '例如157.0',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
INSERT INTO `plee_platform`.`test666` (`id`,`VERSION`,`test`) VALUES ('3','1.3','153.0'); 
