#数字化工艺系统IB2P数据库

# set table IB2P
DROP TABLE IF EXISTS `IB2P_Basic`;
CREATE TABLE `IB2P_Basic`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',
`cartype_name` VARCHAR(20) NOT NULL COMMENT '车型名称',

`IMPORT-REF_DOCREF` VARCHAR(1000) NOT NULL COMMENT 'IB2P的file名字，例如IB1_0009_SAM_MEB_V1_7.xml',
`IB2P_DOC-INFO` VARCHAR(20) COMMENT 'DOC-INFO',
`IB2P_IB-DESCRIPTION` VARCHAR(20) COMMENT 'IB-DESCRIPTION',
`IB2P_PROCEDURES` VARCHAR(20) COMMENT 'PROCEDURES',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB2P_DOC-INFO`;
CREATE TABLE `IB2P_DOC-INFO`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',

`DOC-REVISIONS_VERSION` VARCHAR(500) NOT NULL COMMENT 'IB2P的历史更新版本，例如0_3_DRAFT_1',
`DOC-REVISIONS_DATE` VARCHAR(20) NOT NULL COMMENT 'IB2P的更改日期，例如07.11.2018',
`DOC-REVISIONS_CHANGE` VARCHAR(1000) NOT NULL COMMENT 'IB2P的change log，例如Ergenisspeicher prüfen: DTC´s ergänzt',
`DOC-REVISIONS_TOOL` VARCHAR(50) COMMENT 'IB2P的工具，例如IPPP_V4',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB2P_PROCEDURES`;
CREATE TABLE `IB2P_PROCEDURES`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',

`IB2P_PROCEDURES_IB-1-BLOCK` VARCHAR(50) COMMENT '例如IB2P_IB-1-BLOCK',
`IB2P_PROCEDURES_IB-2-BLOCK` VARCHAR(50) COMMENT '例如IB2P_IB-1-BLOCK',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB2P_PROCEDURES_IB-1-BLOCK`;
CREATE TABLE `IB2P_PROCEDURES_IB-1-BLOCK`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',

`optional` VARCHAR(10) NOT NULL COMMENT '例如ture',
`ADDITIONAL-DESC` VARCHAR(1000) COMMENT '例如erforderlich für Übernahme der HMI-Defaul',
`AREA` VARCHAR(500) COMMENT '例如No Recommendation',
`ADDITIONAL-CONDITIONS-MANUAL-OPTIONS` VARCHAR(10) NOT NULL COMMENT '例如ture',
`IBNZ_VSI` DOUBLE(12,6) COMMENT 'BLOCK中IB1的IBNZ时间',
`ADDITIONAL-TAGS-TAG` VARCHAR(100) NOT NULL COMMENT 'IBNZ aus SG-Einzeltest BCM37 VW483',

`cartype_name` VARCHAR(20) NOT NULL COMMENT '车型名称',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB2P_PROCEDURES_IB-2-BLOCK`;
CREATE TABLE `IB2P_PROCEDURES_IB-2-BLOCK`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',

`IMPORT-REF_DOCREF` VARCHAR(1000) NOT NULL COMMENT 'IB2P的file名字，例如IB1_0009_SAM_MEB_V1_7.xml',
`KD-relevant` VARCHAR(10) NOT NULL COMMENT '例如ture',
`P-relevant` VARCHAR(10) NOT NULL COMMENT '例如ture',
`optional` VARCHAR(10) NOT NULL COMMENT '例如ture',
`standardIBNB` VARCHAR(10) NOT NULL COMMENT '例如ture',
`NAME` VARCHAR(200) NOT NULL COMMENT '例如Wertschoepfungspruefung Heckklappenentriegelung aussen',
`DESC` VARCHAR(1000) COMMENT '例如Die Abhaengingkeit zum Fahrzeuggeschwindikeitssignal und zur Stell',
`CATEGORY` VARCHAR(100) NOT NULL COMMENT '例如Wertschoepfungspruefung Heckklappenentriegelung aussen',
`TAGS-TAG` VARCHAR(100) NOT NULL COMMENT '例如IBNZ aus SG-Einzeltest BCM37 VW483',
`LOGICAL-LINK` VARCHAR(100) NOT NULL COMMENT '例如CentrElectUDS',
`CONDITONS_MANUAL-OPERATIONS` VARCHAR(100) NOT NULL COMMENT '例如ture',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB2P_PROCEDURES_IB-2-BLOCK_STEP`;
CREATE TABLE `IB2P_PROCEDURES_IB-2-BLOCK_STEP`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',

`cyclic` VARCHAR(20) NOT NULL COMMENT '例如ture',
`NAME` VARCHAR(200) NOT NULL COMMENT '例如Messwert pruefen',
`TIS_TI` VARCHAR(100) COMMENT '例如SER00069',
`TIME-PARAMETER_VALUE-PROXY_VALUE` VARCHAR(100) COMMENT '例如500 ms',
`DESC` VARCHAR(1000) NOT NULL COMMENT '例如Messwert parallel zur manuellenTaetigkeit auf "betaetigt/actuated" auslesen.',
`DIAG-SERVICE` VARCHAR(50) COMMENT '例如DIAG-SERVICE',
`DIAG-PARAMETERS` VARCHAR(50) COMMENT '例如DIAG-PARAMETERS',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB2P_PROCEDURES_IB-2-BLOCK_STEP_DIAG-SERVICE`;
CREATE TABLE `IB2P_PROCEDURES_IB-2-BLOCK_STEP_DIAG-SERVICE`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',

`IB2P_STEP_id` INT(11) NOT NULL COMMENT 'IB2P_step_id',
`DIAG-SERVICE_SERVICE-IDENTIFIER` VARCHAR(100) COMMENT '例如31',
`DIAG-SERVICE_LONG-NAME` VARCHAR(200) COMMENT '例如Routine Control / Start Basic Setting',
`DIAG-SERVICE_SHORT-NAME` VARCHAR(200) COMMENT '例如DiagnServi_RoutiContrStartBasicSetti',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB2P_PROCEDURES_IB-2-BLOCK_STEP_DIAG-PARAMETERS`;
CREATE TABLE `IB2P_PROCEDURES_IB-2-BLOCK_STEP_DIAG-PARAMETERS`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`IB2P_NAME` VARCHAR(100) NOT NULL COMMENT 'IB2P name，例如 0009_SAM_MEB',
`IB2P_VERSION` VARCHAR(50) NOT NULL COMMENT 'IB2P版本，例如0.24',
`RELEASE-DATE` VARCHAR(20) NOT NULL COMMENT '释放日期，例如21.01.2021',

`IB2P_STEP_id` INT(11) NOT NULL COMMENT 'IB2P_step_id',
`DIAG-PARAMETERS_DATA-IDENTIFIER` VARCHAR(50) COMMENT '例如0977',
`DIAG-PARAMETERS_DIAG-PARAMETER_LONG-NAME` VARCHAR(200) COMMENT '例如Routine Identifier',
`DIAG-PARAMETERS_DIAG-PARAMETER_SHORT-NAME` VARCHAR(200) COMMENT '例如Param_RoutiContrOptioTimer',
`DIAG-PARAMETERS_DIAG-PARAMETER_MESSAGE-TYPE` VARCHAR(50) COMMENT 'REQUEST',
`DIAG-PARAMETERS_DIAG-PARAMETER_VALUE` VARCHAR(100) COMMENT 'Side_Light_Test',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;