package dao;

import pojo.IB1_SECURITY_PROPERTIES_ECU_SECURITY_PROPERTYLei;

import java.util.List;
import java.util.Map;

public interface IB1_SECURITY_PROPERTIES_ECU_SECURITY_PROPERTYMapper {
    //查询IB1_Basic
    List<IB1_SECURITY_PROPERTIES_ECU_SECURITY_PROPERTYLei> getIB1_SECURITY_PROPERTIES_ECU_SECURITY_PROPERTY(Map map);
    List<IB1_SECURITY_PROPERTIES_ECU_SECURITY_PROPERTYLei> getIB1_SECURITY_PROPERTIES_All(Map map);



}
