package dao;

import pojo.IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETERLei;

import java.util.List;
import java.util.Map;

public interface IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETERMapper {
    //查询IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETER
    List<IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETERLei> getIB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETER(Map map);


}
