package pojo;

public class IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG_PARAMETERSLei {

    private String platform_name;
    private String IB1_VERSION;
    private String diagnose_adr;
    private String IB1_NAME;

    private String BLOCK_NAME;
    private String STEP_NAME;

    private String STEP_DIAG_PARAMETERS_DATA_IDENTIFIER;

    private String DIAG_PARAMETER_LONG_NAME;
    private String DIAG_PARAMETER_SHORT_NAME;
    private String DIAG_PARAMETER_MESSAGE_TYPE;
    private String DIAG_PARAMETER_RESPONSE_SHORT_NAME;
    private String DIAG_PARAMETER_PATH;
    private String DIAG_PARAMETER_DATATYPE;
    private String DIAG_PARAMETER_VALUE_PROXY_VALUE;
    private String DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE;
    private String DIAG_PARAMETER_DISPLAYUNIT;

    private IB1_BasicLei IB1_Basic;
    private IB1_PROCEDURES_PROCEDURELei IB1_PROCEDURES_PROCEDURE;
    private IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEPLei IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP;

    public IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG_PARAMETERSLei() {
    }

    public IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG_PARAMETERSLei(String platform_name, String IB1_VERSION, String diagnose_adr, String IB1_NAME, String BLOCK_NAME, String STEP_NAME, String STEP_DIAG_PARAMETERS_DATA_IDENTIFIER, String DIAG_PARAMETER_LONG_NAME, String DIAG_PARAMETER_SHORT_NAME, String DIAG_PARAMETER_MESSAGE_TYPE, String DIAG_PARAMETER_RESPONSE_SHORT_NAME, String DIAG_PARAMETER_PATH, String DIAG_PARAMETER_DATATYPE, String DIAG_PARAMETER_VALUE_PROXY_VALUE, String DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE, String DIAG_PARAMETER_DISPLAYUNIT, IB1_BasicLei IB1_Basic, IB1_PROCEDURES_PROCEDURELei IB1_PROCEDURES_PROCEDURE, IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEPLei IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP) {
        this.platform_name = platform_name;
        this.IB1_VERSION = IB1_VERSION;
        this.diagnose_adr = diagnose_adr;
        this.IB1_NAME = IB1_NAME;
        this.BLOCK_NAME = BLOCK_NAME;
        this.STEP_NAME = STEP_NAME;
        this.STEP_DIAG_PARAMETERS_DATA_IDENTIFIER = STEP_DIAG_PARAMETERS_DATA_IDENTIFIER;
        this.DIAG_PARAMETER_LONG_NAME = DIAG_PARAMETER_LONG_NAME;
        this.DIAG_PARAMETER_SHORT_NAME = DIAG_PARAMETER_SHORT_NAME;
        this.DIAG_PARAMETER_MESSAGE_TYPE = DIAG_PARAMETER_MESSAGE_TYPE;
        this.DIAG_PARAMETER_RESPONSE_SHORT_NAME = DIAG_PARAMETER_RESPONSE_SHORT_NAME;
        this.DIAG_PARAMETER_PATH = DIAG_PARAMETER_PATH;
        this.DIAG_PARAMETER_DATATYPE = DIAG_PARAMETER_DATATYPE;
        this.DIAG_PARAMETER_VALUE_PROXY_VALUE = DIAG_PARAMETER_VALUE_PROXY_VALUE;
        this.DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE = DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE;
        this.DIAG_PARAMETER_DISPLAYUNIT = DIAG_PARAMETER_DISPLAYUNIT;
        this.IB1_Basic = IB1_Basic;
        this.IB1_PROCEDURES_PROCEDURE = IB1_PROCEDURES_PROCEDURE;
        this.IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP = IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP;
    }

    public String getPlatform_name() {
        return platform_name;
    }

    public void setPlatform_name(String platform_name) {
        this.platform_name = platform_name;
    }

    public String getIB1_VERSION() {
        return IB1_VERSION;
    }

    public void setIB1_VERSION(String IB1_VERSION) {
        this.IB1_VERSION = IB1_VERSION;
    }

    public String getDiagnose_adr() {
        return diagnose_adr;
    }

    public void setDiagnose_adr(String diagnose_adr) {
        this.diagnose_adr = diagnose_adr;
    }

    public String getIB1_NAME() {
        return IB1_NAME;
    }

    public void setIB1_NAME(String IB1_NAME) {
        this.IB1_NAME = IB1_NAME;
    }

    public String getBLOCK_NAME() {
        return BLOCK_NAME;
    }

    public void setBLOCK_NAME(String BLOCK_NAME) {
        this.BLOCK_NAME = BLOCK_NAME;
    }

    public String getSTEP_NAME() {
        return STEP_NAME;
    }

    public void setSTEP_NAME(String STEP_NAME) {
        this.STEP_NAME = STEP_NAME;
    }

    public String getSTEP_DIAG_PARAMETERS_DATA_IDENTIFIER() {
        return STEP_DIAG_PARAMETERS_DATA_IDENTIFIER;
    }

    public void setSTEP_DIAG_PARAMETERS_DATA_IDENTIFIER(String STEP_DIAG_PARAMETERS_DATA_IDENTIFIER) {
        this.STEP_DIAG_PARAMETERS_DATA_IDENTIFIER = STEP_DIAG_PARAMETERS_DATA_IDENTIFIER;
    }

    public String getDIAG_PARAMETER_LONG_NAME() {
        return DIAG_PARAMETER_LONG_NAME;
    }

    public void setDIAG_PARAMETER_LONG_NAME(String DIAG_PARAMETER_LONG_NAME) {
        this.DIAG_PARAMETER_LONG_NAME = DIAG_PARAMETER_LONG_NAME;
    }

    public String getDIAG_PARAMETER_SHORT_NAME() {
        return DIAG_PARAMETER_SHORT_NAME;
    }

    public void setDIAG_PARAMETER_SHORT_NAME(String DIAG_PARAMETER_SHORT_NAME) {
        this.DIAG_PARAMETER_SHORT_NAME = DIAG_PARAMETER_SHORT_NAME;
    }

    public String getDIAG_PARAMETER_MESSAGE_TYPE() {
        return DIAG_PARAMETER_MESSAGE_TYPE;
    }

    public void setDIAG_PARAMETER_MESSAGE_TYPE(String DIAG_PARAMETER_MESSAGE_TYPE) {
        this.DIAG_PARAMETER_MESSAGE_TYPE = DIAG_PARAMETER_MESSAGE_TYPE;
    }

    public String getDIAG_PARAMETER_RESPONSE_SHORT_NAME() {
        return DIAG_PARAMETER_RESPONSE_SHORT_NAME;
    }

    public void setDIAG_PARAMETER_RESPONSE_SHORT_NAME(String DIAG_PARAMETER_RESPONSE_SHORT_NAME) {
        this.DIAG_PARAMETER_RESPONSE_SHORT_NAME = DIAG_PARAMETER_RESPONSE_SHORT_NAME;
    }

    public String getDIAG_PARAMETER_PATH() {
        return DIAG_PARAMETER_PATH;
    }

    public void setDIAG_PARAMETER_PATH(String DIAG_PARAMETER_PATH) {
        this.DIAG_PARAMETER_PATH = DIAG_PARAMETER_PATH;
    }

    public String getDIAG_PARAMETER_DATATYPE() {
        return DIAG_PARAMETER_DATATYPE;
    }

    public void setDIAG_PARAMETER_DATATYPE(String DIAG_PARAMETER_DATATYPE) {
        this.DIAG_PARAMETER_DATATYPE = DIAG_PARAMETER_DATATYPE;
    }

    public String getDIAG_PARAMETER_VALUE_PROXY_VALUE() {
        return DIAG_PARAMETER_VALUE_PROXY_VALUE;
    }

    public void setDIAG_PARAMETER_VALUE_PROXY_VALUE(String DIAG_PARAMETER_VALUE_PROXY_VALUE) {
        this.DIAG_PARAMETER_VALUE_PROXY_VALUE = DIAG_PARAMETER_VALUE_PROXY_VALUE;
    }

    public String getDIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE() {
        return DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE;
    }

    public void setDIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE(String DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE) {
        this.DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE = DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE;
    }

    public String getDIAG_PARAMETER_DISPLAYUNIT() {
        return DIAG_PARAMETER_DISPLAYUNIT;
    }

    public void setDIAG_PARAMETER_DISPLAYUNIT(String DIAG_PARAMETER_DISPLAYUNIT) {
        this.DIAG_PARAMETER_DISPLAYUNIT = DIAG_PARAMETER_DISPLAYUNIT;
    }

    public IB1_BasicLei getIB1_Basic() {
        return IB1_Basic;
    }

    public void setIB1_Basic(IB1_BasicLei IB1_Basic) {
        this.IB1_Basic = IB1_Basic;
    }

    public IB1_PROCEDURES_PROCEDURELei getIB1_PROCEDURES_PROCEDURE() {
        return IB1_PROCEDURES_PROCEDURE;
    }

    public void setIB1_PROCEDURES_PROCEDURE(IB1_PROCEDURES_PROCEDURELei IB1_PROCEDURES_PROCEDURE) {
        this.IB1_PROCEDURES_PROCEDURE = IB1_PROCEDURES_PROCEDURE;
    }

    public IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEPLei getIB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP() {
        return IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP;
    }

    public void setIB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP(IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEPLei IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP) {
        this.IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP = IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP;
    }

    @Override
    public String toString() {
        return "IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG_PARAMETERSLei{" +
                "platform_name='" + platform_name + '\'' +
                ", IB1_VERSION='" + IB1_VERSION + '\'' +
                ", diagnose_adr='" + diagnose_adr + '\'' +
                ", IB1_NAME='" + IB1_NAME + '\'' +
                ", BLOCK_NAME='" + BLOCK_NAME + '\'' +
                ", STEP_NAME='" + STEP_NAME + '\'' +
                ", STEP_DIAG_PARAMETERS_DATA_IDENTIFIER='" + STEP_DIAG_PARAMETERS_DATA_IDENTIFIER + '\'' +
                ", DIAG_PARAMETER_LONG_NAME='" + DIAG_PARAMETER_LONG_NAME + '\'' +
                ", DIAG_PARAMETER_SHORT_NAME='" + DIAG_PARAMETER_SHORT_NAME + '\'' +
                ", DIAG_PARAMETER_MESSAGE_TYPE='" + DIAG_PARAMETER_MESSAGE_TYPE + '\'' +
                ", DIAG_PARAMETER_RESPONSE_SHORT_NAME='" + DIAG_PARAMETER_RESPONSE_SHORT_NAME + '\'' +
                ", DIAG_PARAMETER_PATH='" + DIAG_PARAMETER_PATH + '\'' +
                ", DIAG_PARAMETER_DATATYPE='" + DIAG_PARAMETER_DATATYPE + '\'' +
                ", DIAG_PARAMETER_VALUE_PROXY_VALUE='" + DIAG_PARAMETER_VALUE_PROXY_VALUE + '\'' +
                ", DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE='" + DIAG_PARAMETER_VALUE_PROXY_TOLERANCE_MAX_VALUE + '\'' +
                ", DIAG_PARAMETER_DISPLAYUNIT='" + DIAG_PARAMETER_DISPLAYUNIT + '\'' +
                ", IB1_Basic=" + IB1_Basic +
                ", IB1_PROCEDURES_PROCEDURE=" + IB1_PROCEDURES_PROCEDURE +
                ", IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP=" + IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP +
                '}';
    }
}
