#数字化工艺系统IB3P数据库

# set table IB3P
DROP TABLE IF EXISTS `IB3P_Basic`;
CREATE TABLE `IB3P_Basic`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`cartype_name` VARCHAR(20) NOT NULL COMMENT '车型名称,例如：VW316/6_CN_B（11G）',
`diagnose_adr` VARCHAR(6) COMMENT '诊断地址',
`SG_name` VARCHAR(100) COMMENT '控制器名字缩写',

`IB3P_VERSION` VARCHAR(20) COMMENT 'IB3P_VERSION，例如 VW316_6CN_B',
`IB3P_RELEASE-DATE` VARCHAR(20) COMMENT '释放日期，例如22.01.2021',
`IB3P_filename` VARCHAR(1000) COMMENT '例如IB3P_SYSTEM_VW316_6CN_B_0052 - Türelektronik Beifahrer_TSG_BFS_MQB37W_MEB_V1_4_SUB_1.xml',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO `plee_platform`.`IB3P_Basic` (`id`,`cartype_name`,`diagnose_adr`,`SG_name`,`IB3P_VERSION`,`IB3P_RELEASE-DATE`,`IB3P_filename`) VALUES ('1','VW316/6_CN_B（11G）','0001','ELV','V1_1','22.01.2021','IB3P_SYSTEM_VW316_6CN_B_0052 - Türelektronik Beifahrer_TSG_BFS_MQB37W_MEB_V1_4_SUB_1.xml'); 
