server:
  port: 8888

spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.227.6.242:3306/plee_platform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: Liang.Dongyu
      password: faw123
      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量
      max-active: 30

      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000

      # 当程序存在缺陷时，申请的连接忘记关闭，这时候，就存在连接泄漏了。
      # Druid提供了RemoveAbandanded相关配置，用来关闭长时间不使用的连接。
      # RemoveAbandanded功能不建议在生产环境中使用，仅用于连接泄露检测诊断。
      # 超过时间限制是否回收
      #removeAbandoned: true
      # 当连接超过3分钟后会强制进行回收
      #removeAbandonedTimeout: 180
      #      打开PSCache，并且指定每个连接上PSCache的大小
      #pool-prepared-statements: true
      #max-pool-prepared-statement-per-connection-size: 20
      #      间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #time-between-eviction-runs-millis: 60000
      #min-evictable-idle-time-millis: 300000
      #max-evictable-idle-time-millis: 60000
      #用来检测连接是否有效的sql 必须是一个查询语句。mysql中为 select 'x'， oracle中为 select 1 from dual
      #validation-query: select 'x'
      # validation-query-timeout: 5000
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      #test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      #test-on-return: false
      #test-while-idle: true
      #通过connectProperties属性来打开mergeSql功能，慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入)
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #配置stat-view-servlet
      stat-view-servlet:
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow:
        #允许开启监控
        enabled: true
        #监控面板路径
        url-pattern: /druid/*
        login-username: admin
        login-password: root
        #是否可以重置
        reset-enable: true



      # 配置StatFilter
      web-stat-filter:
      #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis:
  type-aliases-package: com.fawvw.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

