CREATE DATABASE PLEE_Cloud_Diagnose CHARACTER SET utf8 COLLATE utf8_general_ci
USE PLEE_Cloud_Diagnose;

DROP TABLE IF EXISTS `VBV`;

CREATE TABLE `VBV`(
`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'VBV ID，是主键，唯一的',
`VBV Name` VARCHAR(15) NOT NULL COMMENT 'VBV名字',
`Version` VARCHAR(11) NOT NULL COMMENT 'VBV版本',
#`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
#`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

============================================================================================

DROP TABLE IF EXISTS `ECU`;

CREATE TABLE `ECU`(
`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`VBV ID` INT(11) NOT NULL COMMENT 'VBV ID，与VBV表中ID一致',
`Diag_M` VARCHAR(6) NOT NULL COMMENT '主控制器诊断地址',
`Diag_S` VARCHAR(6) NOT NULL COMMENT '从控制器诊断地址',
`ECU_Name` VARCHAR(15) NOT NULL COMMENT '控制器名字',
`M_or_S` VARCHAR(10) NOT NULL COMMENT 'Master或Slave',
`ECU_M` VARCHAR(6) COMMENT '该控制器的主控制器',
`Login_Code` VARCHAR(6) COMMENT '控制器登陆码',
`ZDC_Sequence` VARCHAR(30)  COMMENT 'ZDC编码顺序',
`PRN` VARCHAR(1000) NOT NULL COMMENT 'PR号',
`TNR` VARCHAR(11) NOT NULL COMMENT '控制器零件号',
`HW_V` VARCHAR(6) NOT NULL COMMENT '控制器硬件版本',
`SW_V` VARCHAR(6) NOT NULL COMMENT '控制器软件版本',
`ZDC_File` VARCHAR(100) COMMENT 'ZDC文件名',
`Flash_File` VARCHAR(100) COMMENT '刷新Flash文件名',
`Wait_Time` VARCHAR(50) COMMENT '等待时间',
`Addre_Lengt_Forma_Ident` VARCHAR(2) COMMENT '未知',
`CKD` VARCHAR(6) COMMENT 'CKD还是LC',
`ZdcOK` BOOLEAN COMMENT 'ZDC合格否',
`FLOk` BOOLEAN COMMENT '刷新合格否',
`SecurityOK` BOOLEAN COMMENT '安全登录合格否',
`Basic_Setting` BOOLEAN COMMENT '基础设置合格否',
#`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
#`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

============================================================================================

DROP TABLE IF EXISTS `Vehicle`;

CREATE TABLE `Vehicle`(
`Vin` VARCHAR(20) NOT NULL COMMENT '底盘号，主键',
`PRN` VARCHAR(1000) NOT NULL COMMENT 'PR号',
`VBV ID` INT(11) NOT NULL COMMENT 'VBV ID，与VBV表中ID一致',
#`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
#`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`Vin`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;



============================================================================================

DROP TABLE IF EXISTS `Operation Log`;
CREATE TABLE `Operation Log`(
`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`User` VARCHAR(20) NOT NULL COMMENT '用户',
`Time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`Operation` VARCHAR(20) NOT NULL COMMENT '操作动作',
`Vin` VARCHAR(20) COMMENT '底盘号',
`Object` VARCHAR(20) NOT NULL COMMENT '操作对象',
`Result` VARCHAR(10) COMMENT '结果',
`Comment` VARCHAR(100) COMMENT '操作描述',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

============================================================================================

DROP TABLE IF EXISTS `Report`;
CREATE TABLE `Report`(
`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
`User` VARCHAR(20) NOT NULL COMMENT '用户',
`Time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`Vin` VARCHAR(20) NOT NULL COMMENT '底盘号',
`Path` VARCHAR(20) NOT NULL COMMENT '报告存储路径',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
