package dao;

import pojo.IB1_ENVIRONMENT_PRODUCTION_MODES_PRODUCTION_MODELei;

import java.util.List;
import java.util.Map;

public interface IB1_ENVIRONMENT_PRODUCTION_MODES_PRODUCTION_MODEMapper {
    //查询IB1_Basic
    List<IB1_ENVIRONMENT_PRODUCTION_MODES_PRODUCTION_MODELei> getIB1_ENVIRONMENT_PRODUCTION_MODES_PRODUCTION_MODE(Map map);



}
