# establish IB1 Database

# 1.1 set IB1_Basic table
DROP TABLE IF EXISTS `IB1_Basic`;
CREATE TABLE `IB1_Basic`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`IB1_RELEASE-DATE` VARCHAR(20) COMMENT '释放日期，例如11.07.2019',
`IB1_IBN-REQUIRED` VARCHAR(20) COMMENT '例如true',

#`IB1_DOC-INFO_DOC-REVISIONS_DOC-REVISION` VARCHAR(50) COMMENT '例如VERSION',
#`IB1_IB-DESCRIPTION` VARCHAR(50) COMMENT '例如IB-VARIANTS',
#`IB1_ENVIRONMENT` VARCHAR(50) COMMENT '例如PRE-CONDITIONS',
#`IB1_PROCEDURES_BLOCK` VARCHAR(50) COMMENT '例如KD-relevant',
#`IB1_BZD_IDENTS_IDENT` VARCHAR(50) COMMENT '例如NAME',
#`IB1_REFERENCES_RELATED-DOCUMENTS_RELATED-DOCUMENT` VARCHAR(50) COMMENT '例如NAME',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
### 1.2 set IB1_DOC-INFO(include CONTACTS and REVISIONS)
DROP TABLE IF EXISTS `IB1_DOC-INFO_CONTACTS`;
CREATE TABLE `IB1_DOC-INFO_CONTACTS`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`NAME` VARCHAR(50) COMMENT 'Erik Hartmann',
`COMPANY` VARCHAR(50) COMMENT 'Volkswagen AG',
`DEPARTMENT` VARCHAR(50) COMMENT 'EESD/3',
`ROLE` VARCHAR(50) COMMENT 'Bauteilentwickler',
`PHONE` VARCHAR(50) COMMENT '+49-5361-9-13492',
`MAIL` VARCHAR(100) COMMENT 'Erik.Hartmann@volkswagen.de',


`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
DROP TABLE IF EXISTS `IB1_DOC-INFO_DOC-REVISIONS`;
CREATE TABLE `IB1_DOC-INFO_DOC-REVISIONS`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`VERSION` VARCHAR(20)  COMMENT '1_0',
`DATE` VARCHAR(20)  COMMENT '07.08.2018',
`CHANGE` VARCHAR(1000) COMMENT 'Erstbefüllung',
`TOOL` VARCHAR(50) COMMENT '例如IPPP_V4',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
### 1.3 set IB1_IB-DESCRIPTION

#IB1_IB-DESCRIPTION_IB-VARIANTS
DROP TABLE IF EXISTS `IB1_IB-DESCRIPTION_IB-VARIANTS`;
CREATE TABLE `IB1_IB-DESCRIPTION_IB-VARIANTS`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`NAME` VARCHAR(100) COMMENT 'Med',
`DESC` VARCHAR(100) COMMENT '1EA.937.084.*',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

#IB1_IB-DESCRIPTION_OBJECTIVES
DROP TABLE IF EXISTS `IB1_IB-DESCRIPTION_OBJECTIVES`;
CREATE TABLE `IB1_IB-DESCRIPTION_OBJECTIVES`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`text` VARCHAR(200) COMMENT 'Verbauprüfung',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

#IB1_IB-DESCRIPTION_IBNZ
DROP TABLE IF EXISTS `IB1_IB-DESCRIPTION_IBNZ`;
CREATE TABLE `IB1_IB-DESCRIPTION_IBNZ`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`IBNZ-ESTIMATION` VARCHAR(100) COMMENT '157.0',
`IBNZ-COMMITMENT` VARCHAR(100) COMMENT '157.0',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
#IB1_IB-DESCRIPTION_SLAVE
DROP TABLE IF EXISTS `IB1_IB-DESCRIPTION_SLAVE`;
CREATE TABLE `IB1_IB-DESCRIPTION_SLAVE`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`NAME` VARCHAR(100) COMMENT '157.0',
`ECU-ID` VARCHAR(10) COMMENT '157.0',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
#========================================================
### 1.4 set IB1_IB-DESCRIPTION_ENVIRONMENT

#IB1_ENVIRONMENT_PRE-CONDITIONS_PRE-CONDITION
DROP TABLE IF EXISTS `IB1_ENVIRONMENT_PRE-CONDITIONS_PRE-CONDITION`;
CREATE TABLE `IB1_ENVIRONMENT_PRE-CONDITIONS_PRE-CONDITION`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',


`kdRelevant` VARCHAR(20) COMMENT '例如true',
`pRelevant` VARCHAR(20) COMMENT '例如true',
`text` VARCHAR(1000) COMMENT 'Bordnetzspannungspegel ≥ 12 V, CAN Kommunikation, Kl. 15 aktiv (Klemmensteuerung berücksichtigen)',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
#IB1_ENVIRONMENT_DEPENDENCIES_DEPENDENCY
DROP TABLE IF EXISTS `IB1_ENVIRONMENT_DEPENDENCIES_DEPENDENCY`;
CREATE TABLE `IB1_ENVIRONMENT_DEPENDENCIES_DEPENDENCY`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',


`text` VARCHAR(1000) COMMENT '例如Verbauänderung am Komfort CAN bzw. SubCAN',


`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_ENVIRONMENT_ACCESS-AUTHORISATIONS_ACCESS-AUTHORISATION`;
CREATE TABLE `IB1_ENVIRONMENT_ACCESS-AUTHORISATIONS_ACCESS-AUTHORISATION`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`NAME` VARCHAR(100) COMMENT '例如SFD',
`DESC` VARCHAR(1000) COMMENT '例如Diagnose wird über SFD geschützt',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB1_ENVIRONMENT_PRODUCTION-MODES_PRODUCTION-MODE`;
CREATE TABLE `IB1_ENVIRONMENT_PRODUCTION-MODES_PRODUCTION-MODE`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`NAME` VARCHAR(100) COMMENT '例如p_mode_parking_coordinator',
`DESC` VARCHAR(1000) COMMENT '例如PaCo: P-Mode ParkkoordinatorDeaktivierung',
`BYTE-0` VARCHAR(50) COMMENT '例如xxxxxxx1',
`BYTE-1` VARCHAR(50) COMMENT '例如xxxxxxxx',
`BYTE-2` VARCHAR(50) COMMENT '例如xxxxxxxx',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
### 1.5 set IB1_PROCEDURES

# 1.5.1  IB1_PROCEDURES_PROCEDURE
DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`PROCEDURE_NAME` VARCHAR(100) COMMENT 'Inbetriebnahme-Ablauf',

`BLOCK_KD-relevant` VARCHAR(20) NOT NULL COMMENT '例如ture',
`BLOCK_P-relevant` VARCHAR(20) NOT NULL COMMENT '例如ture',
`BLOCK_optional` VARCHAR(20) NOT NULL COMMENT '例如ture',
`BLOCK_shortname` VARCHAR(50) COMMENT '例如UnlockSfd',
`BLOCK_standardIBNB` VARCHAR(20) COMMENT '例如ture',
`BLOCK_version` VARCHAR(20) COMMENT '例如1',
`BLOCK_NAME` VARCHAR(100) COMMENT '例如SFD freischalten',
`BLOCK_NAME_EN` VARCHAR(100) COMMENT '例如SFD unlock',
`BLOCK_DESC` VARCHAR(2000) COMMENT '例如Der Schutz der Fahrzeugdiagnose (SFD) wird ',
#`BLOCK_TIS_TI_TI` VARCHAR(100) COMMENT '例如SER00098',
#`BLOCK_CATEGORY` VARCHAR(100) COMMENT '例如Inbetriebnahme (konstruktiv bedingt)',
`BLOCK_TAGS_TAG` VARCHAR(100) COMMENT '例如IBNZ VSI-Wert aus Gateway MQB37W',
`BLOCK_AREA` VARCHAR(100) COMMENT '例如No Recommendation',
`BLOCK_LOGICAL-LINK` VARCHAR(50) COMMENT '例如GatewUDS',
`BLOCK_CONDITIONS_MANUAL-OPERATIONS` VARCHAR(20) COMMENT '例如false',
`BLOCK_IBNZ_VSI` DOUBLE(12,6) COMMENT '例如0.312',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================

DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETER`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE_BLOCK_PARAMETERS_PARAMETER`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`BLOCK_NAME` VARCHAR(100) COMMENT '例如SFD freischalten',

`BLOCK_PARAMETERS_PARAMETER_optional` VARCHAR(20) COMMENT '例如ture',
`BLOCK_PARAMETERS_PARAMETER_KEY` VARCHAR(100) COMMENT '例如Aufstartzeit',
`BLOCK_PARAMETERS_PARAMETER_DESC` VARCHAR(1000) COMMENT '例如Aufstartzeit in Sekunden',
`BLOCK_PARAMETERS_PARAMETER_DATATYPE` VARCHAR(100) COMMENT '例如Integer',
`BLOCK_PARAMETERS_PARAMETER_VALUE` VARCHAR(100) COMMENT '例如&lt;1',
`BLOCK_PARAMETERS_PARAMETER_DEFAULT` VARCHAR(50) COMMENT '例如2',


`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`BLOCK_NAME` VARCHAR(100) COMMENT '例如SFD freischalten',

#`cyclic` VARCHAR(20) COMMENT '例如false',
`STEP_NAME` VARCHAR(100) COMMENT '例如VW/Audi-Teilenummer lesen',
`STEP_DESC` VARCHAR(1000) COMMENT '例如Fuer die Ermittlung des Herstellercodes (HSC)',
`STEP_DIAG-SERVICE-IDENTIFIER` VARCHAR(100) COMMENT '例如SERVICE-IDENTIFIER',
`STEP_DIAG-SERVICE-LONG-NAME` VARCHAR(100) COMMENT '例如Read Data By Identifier / ECU Identification',
`STEP_DIAG-SERVICE-SHORT-NAME` VARCHAR(100) COMMENT '例如DiagnServi_ReadDataByIdentECUIdent',

`STEP_DIAG-PARAMETERS_DATA-IDENTIFIER` VARCHAR(20) COMMENT '例如F187',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================
DROP TABLE IF EXISTS `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG-PARAMETERS`;
CREATE TABLE `IB1_PROCEDURES_PROCEDURE_BLOCK_STEPS_STEP_DIAG-PARAMETERS`(

`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`BLOCK_NAME` VARCHAR(100) COMMENT '例如SFD freischalten',
`STEP_NAME` VARCHAR(100) COMMENT '例如VW/Audi-Teilenummer lesen',

`DIAG-PARAMETER_LONG-NAME` VARCHAR(100) COMMENT '例如Record Data Identifier',
`DIAG-PARAMETER_SHORT-NAME` VARCHAR(100) COMMENT '例如Param_RecorDataIdent',
`DIAG-PARAMETER_MESSAGE-TYPE` VARCHAR(100) COMMENT '例如REQUEST',
`DIAG-PARAMETER_RESPONSE-SHORT-NAME` VARCHAR(100) COMMENT '例如Resp_ReadDataByIdentECUIdent',
`DIAG-PARAMETER_PATH` VARCHAR(100) COMMENT '例如Param_RecorDataIdent',
`DIAG-PARAMETER_DATATYPE` VARCHAR(100) COMMENT '例如eTEXTTABLE',
`DIAG-PARAMETER_VALUE-PROXY_VALUE` VARCHAR(100) COMMENT '例如VW Spare Part Number',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

#========================================================
### 1.6 set IB1_BZD


DROP TABLE IF EXISTS `IB1_BZD`;
CREATE TABLE `IB1_BZD`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`S42-ATTRIBUTES-ADDED` VARCHAR(20) COMMENT '例如false',
`IDENTS_IDENT_NAME` VARCHAR(100) COMMENT '例如TBD',
`IDENTS_IDENT_S42-ATTRIBUTE` VARCHAR(100) COMMENT '例如TBD',
`IDENTS_IDENT_BGONLINE` VARCHAR(100) COMMENT '例如TBD',
`IDENTS_IDENT_DID` VARCHAR(100) COMMENT '例如TBD',
`TARGET-DATE` VARCHAR(20) COMMENT '例如31.08.2018',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
#========================================================

DROP TABLE IF EXISTS `IB1_REFERENCES_RELATED-DOCUMENTS_RELATED-DOCUMENT`;
CREATE TABLE `IB1_REFERENCES_RELATED-DOCUMENTS_RELATED-DOCUMENT`(
`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',

`platform_name` VARCHAR(20) COMMENT 'MEB',
`IB1_VERSION` VARCHAR(50) COMMENT '1.7',
`diagnose_adr` VARCHAR(6) COMMENT '0009',
`IB1_NAME` VARCHAR(100) COMMENT 'SAM_MEB',

`NAME` VARCHAR(50) COMMENT '例如Zusatzschaltplan',
`VERSION` VARCHAR(50) COMMENT '例如TBD',
`FILE-SYSTEM` VARCHAR(50) COMMENT 'System42',
`SPARE-PART-NUMBER` VARCHAR(200) COMMENT 'TLD.011.179.B0',
`URL` VARCHAR(500) COMMENT 'https://iproject3.wob.vw.vwg/vw',

`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;


